##########
# collectionbuilder-csv
# Jekyll Digital Collection Generator
# https://github.com/CollectionBuilder/collectionbuilder-csv
##########

##########
# URL VARIABLES
#
# site domain, full URL to the production location of your collection
url: 
# path to location on the domain if necessary e.g. /digital/hjccc
baseurl: 
# location of code, the full url to your github repository
source-code: https://github.com/CollectionBuilder/collectionbuilder-csv

##########
# SITE SETTINGS
#
# title of site appears in banner
title: The Leigh Hunt Hair Book
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: A collection of hair complied by the English critic, essayist, and poet J.H. Leigh Hunt.
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: The Leigh Hunt Hair Book exhibits the hair of 21 subjects, collected and compiled by J.H. Leigh Hunt in the 19th century. Notes on Book's material aspects and the provenance of the individual locks.
# keywords, a short list of subjects describing the collection, separated by semicolon, to appear in rich markup
keywords: leigh hunt; john milton
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: Dr. Teri Fickling; Makayla Baughman

##########
# COLLECTION SETTINGS
#
# Set the metadata for your collection (the name of the CSV file in your _data directory that describes the objects in your collection) 
# Use the filename of your CSV **without** the ".csv" extension! E.g. _data/demo-metadata.csv --> "demo-metadata"
metadata: projectmetadatawthumbnails
# page generation settings [optional!]
# [optional: only used if you need to tweak CB defaults or generate from more than one data file]
# page_gen:
#   - data: 
#     template: 
#     name: 
#     dir: 
#     extension: 
#     filter: 

##########
# Site/Organization Branding 
#   Enter information for your organization (replacing the CDIL links and name below) if you'd like to brand your site with a logo
#   To remove the branding, comment out these values, or delete them. 
#
organization-name:
organization-link: 
organization-logo-banner: 
organization-logo-nav: 

##########
# GOOGLE SERVICES [optional!]
#
# leave these blank or comment out to NOT include google code
# if present, used to add analytics during "production" build only
# google-analytics-id: "G-XXXXXXXXX"
# google-cse-id: "002151703305773322890:1pu3smhw1t8"

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE, CITATION.cff, CODE_OF_CONDUCT.md, CONTRIBUTING.md, SECURITY.md]
# compress CSS output
sass:
  style: compressed
